### ISSUE TITLE
[Documentation] Linux setup

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/django-concept#40] opened 2020-01-14 10:37 UTC
## Context
In a hangout last week, @bengineerdavis and I discussed documenting some Linux-specific setup instructions for this project, assuming setting up postgres in a docker container is doable.

## Acceptance Criteria
- [ ] Add to the README.md a section re: Linux-specific instructions for getting the Django app running and a Docker Postgres instance running.

**Comment by billglover** [comment] 2020-01-16 15:25
Does this get resolved by #41?

**Comment by bengineerdavis** [comment] 2020-01-16 18:18
@billglover Just talked to @lpatmo and will confirm setup for Fedora 30 over at #41.

**Comment by wuworkshop** [comment] 2020-01-16 23:19
So who will be testing this on Windows? 😅 I always feel bad that Windows users tend to get the short end of the stick.

**Comment by lpatmo** [comment] 2020-01-17 08:34
> So who will be testing this on Windows? 

Good question! @nuageklow If I remember correctly, you are on Windows? If so, any chance you'd like to test https://github.com/codebuddies/django-concept/pull/44?

**Comment by bengineerdavis** [comment] 2020-01-21 03:06
I've run into some forking challenges, likely with the way GitHub manages them, and would like to consider making this it's own feature branch or sub-feature branch of dev setup: #51

**Comment by bengineerdavis** [comment] 2020-01-21 03:08
Per 'acceptance criteria': 

- [ ] specify the distro(s), mostly because we only want to confirm for the ones we've used to make this setup work. 

- [ ] Confirm any libraries or other utilities required, such as Docker.

- [ ] How to new contributions/preferences. #3

**Comment by sebbel** [comment] 2020-01-30 19:23
Hey @bengineerdavis, I am on Ubuntu 18.04 and can confirm that the project works out of the box with @billglover Docker additions

**Comment by billglover** [comment] 2020-02-02 21:03
With #44 merged and confirmed working on Ubuntu 18.04 I'm marking this as closed. The instructions assume you have docker installed, but have been tested on Windows 10 Pro, Linux, and Mac OS.

**Closed by billglover** 2020-02-02 21:03 UTC
Labels: documentation

**Comment by bengineerdavis** [comment] 2020-02-03 04:25
Thank you Sebbel!
